name: gizi_sehat_mobile_app
description: "A mobile app for smart nutrition analysis and family health assistant (GiziSehat)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ---- UI & State Management ----
  provider: ^6.1.2         # untuk state management di auth_provider, dll
  flutter_bloc: ^8.1.6     # kalau nanti kamu pakai BLoC pattern di dashboard/ai_chat
  equatable: ^2.0.5        # bantu BLoC event/state equality

  # ---- Firebase & Database ----
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3

  # ---- API & Network ----
  http: ^1.2.2
  dio: ^5.5.0              # opsional, kalau mau lebih advanced dari http

  # ---- Lokasi & Maps ----
  geolocator: ^11.0.0
  google_maps_flutter: ^2.7.0

  # ---- AI / Gemini ----
  google_generative_ai: ^0.3.2  # paket resmi Google Gemini API

  # ---- UI tambahan ----
  flutter_svg: ^2.0.10
  intl: ^0.19.0

  # ---- Shared Preferences / Config ----
  shared_preferences: ^2.5.3

  # ---- Lainnya ----
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/