name: gizi_sehat_mobile_app
description: "A mobile app for smart nutrition analysis and family health assistant (GiziSehat)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # ---- UI & State Management ----
  provider: ^6.1.2         # untuk state management di auth_provider, dll

  # ---- Firebase & Database ----
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  google_sign_in: ^6.2.1  # untuk Google Sign-In
  google_generative_ai: ^0.4.0

  # ---- UI tambahan ----
  intl: ^0.19.0

  # ---- Shared Preferences / Config ----
  shared_preferences: ^2.5.3

  # ---- Lainnya ----
  flutter_native_splash: ^2.4.0
  image_picker: ^1.2.1
  cached_network_image: ^3.3.1
  http: ^1.6.0
  flutter_markdown: ^0.7.7+1
  flutter_gen_ai_chat_ui: ^2.5.0
  fl_chart: ^1.1.1
  google_fonts: ^6.3.3
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  excel: ^4.0.6
  share_plus: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/logo_google.jpg
    - assets/images/Berkas_Google__G__logo.svg
    - assets/data/